
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Isaac Dawson   ## put your name
title: 'NO_TITLE'  ## your title
location: 9999, 99999


## Social Profiles
facebook: NO_FB  ## your facebook account url
twitter: NO_TWITTER  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: NO_DRIBBLE  ## you dribbble account url
foursquare: NO_FAITH_IN_SECURITY  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
